//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntenneInstallate
    {
        public string odl { get; set; }
        public string radio { get; set; }
        public string radioStatus { get; set; }
        public string kit { get; set; }
        public string kitDesc { get; set; }
        public string login { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.DateTime> data_creazione { get; set; }
    }
}
