//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attivazioni_Ordini
    {
        public string hlan { get; set; }
        public string stato { get; set; }
        public Nullable<System.DateTime> data_ordine { get; set; }
        public Nullable<System.DateTime> data_attivazione { get; set; }
        public Nullable<System.DateTime> data_modifica { get; set; }
        public Nullable<bool> importato { get; set; }
    }
}
