//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElencoBTS
    {
        public string id { get; set; }
        public string nome { get; set; }
        public string model_type_desc { get; set; }
        public Nullable<decimal> lat_site { get; set; }
        public Nullable<decimal> long_site { get; set; }
        public Nullable<decimal> altitude_asl { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string login { get; set; }
    }
}
