//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EoloCompensi
    {
        public string itemodl { get; set; }
        public string nome { get; set; }
        public string sla { get; set; }
        public Nullable<System.DateTime> data_intervento { get; set; }
        public Nullable<int> compenso { get; set; }
        public Nullable<int> extra { get; set; }
        public string esito { get; set; }
        public Nullable<System.DateTime> data_inserimento { get; set; }
    }
}
