//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetElencoLog
    {
        public string itemODL { get; set; }
        public System.DateTime data { get; set; }
        public string note { get; set; }
        public string userName { get; set; }
        public string login { get; set; }
    }
}
