//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetElencoKitOdl
    {
        public string itemODL { get; set; }
        public string codice { get; set; }
        public string descrizione { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    }
}
