//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetElenco
    {
        public string itemKEY { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string sla { get; set; }
        public string cliente { get; set; }
        public string indirizzo { get; set; }
        public string cap { get; set; }
        public string comune { get; set; }
        public string pv { get; set; }
        public string contatto { get; set; }
        public string tel { get; set; }
        public string cel { get; set; }
        public string email { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> @long { get; set; }
        public Nullable<System.DateTime> dataAppuntamento { get; set; }
        public string tipoWS { get; set; }
        public string login { get; set; }
        public Nullable<System.DateTime> dataCreazione { get; set; }
        public Nullable<System.DateTime> dataModifica { get; set; }
        public Nullable<bool> myvar { get; set; }
        public Nullable<bool> crm_imported { get; set; }
    }
}
