//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetElencoLinkOdl
    {
        public string id { get; set; }
        public string odl { get; set; }
        public Nullable<decimal> distance { get; set; }
        public Nullable<decimal> tilt { get; set; }
        public Nullable<decimal> azimuth { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string login { get; set; }
        public Nullable<int> ordine { get; set; }
        public Nullable<bool> sconsigliato { get; set; }
    }
}
