//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEsecuzione
    {
        public int LogID { get; set; }
        public Nullable<System.DateTime> DataOraInizioEsecuzione { get; set; }
        public Nullable<System.DateTime> DataOraFineEsecuzione { get; set; }
        public string Stato { get; set; }
        public Nullable<int> NumRecordATTInsert { get; set; }
        public Nullable<int> NumRecordATTUpdate { get; set; }
    }
}
